# Generated by Django 4.2.2 on 2023-06-07 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField(max_length=35)),
                ('competence', models.CharField(max_length=35)),
                ('description2', models.TextField(max_length=25)),
                ('img', models.URLField(max_length=100)),
                ('birthday', models.DateField()),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.BooleanField()),
                ('description3', models.TextField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='FactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=30)),
                ('happy', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('projects', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('hours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('workers', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=60)),
                ('competence', models.CharField(max_length=60)),
            ],
        ),
    ]
