# Generated by Django 4.2.1 on 2023-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.TextField(max_length=35)),
                ('nom', models.TextField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
        migrations.DeleteModel(
            name='FactsModel',
        ),
        migrations.DeleteModel(
            name='HeaderModel',
        ),
    ]
