# Generated by Django 4.2.1 on 2023-06-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_heromodel_delete_aboutmodel_delete_factsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='nom',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='prenom',
            field=models.CharField(max_length=35),
        ),
    ]
