# Generated by Django 4.2.1 on 2023-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skillsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('call', models.CharField(max_length=50)),
            ],
        ),
    ]
